const travelImages = [
  {
    image: "/travel/amsterdam.jpg",
    year: 2018,
    city: "Amsterdam",
    country: "Netherlands",
    index: 1,
  },
  {
    image: "/travel/antwerp.jpg",
    year: 2018,
    city: "Antwerp",
    country: "Belgium",
    index: 2,
  },
  {
    image: "/travel/austin_tacos.jpg",
    year: 2017,
    city: "Austin",
    country: "Texas",
    index: 3,
  },
  {
    image: "/travel/austin.jpg",
    year: 2017,
    city: "Austin",
    country: "Texas",
    index: 4,
  },
  {
    image: "/travel/bellagio.jpg",
    year: 2017,
    city: "Las Vegas",
    country: "Nevada",
    index: 5,
  },
  {
    image: "/travel/beverly_hills.jpg",
    year: 2017,
    city: "Los Angeles",
    country: "California",
    index: 6,
  },
  {
    image: "/travel/brugge.jpg",
    year: 2018,
    city: "Brugge",
    country: "Belgium",
    index: 7,
  },
  {
    image: "/travel/chania.jpg",
    year: 2021,
    city: "Chania",
    country: "Crete",
    index: 8,
  },
  {
    image: "/travel/colosseum.jpg",
    year: 2016,
    city: "Rome",
    country: "Italy",
    index: 9,
  },
  {
    image: "/travel/geneva.jpg",
    year: 2020,
    city: "Geneva",
    country: "Switzerland",
    index: 10,
  },
  {
    image: "/travel/granville_island.jpg",
    year: 2019,
    city: "Vancouver",
    country: "Canada",
    index: 11,
  },
  {
    image: "/travel/griffith.jpg",
    year: 2017,
    city: "Los Angeles",
    country: "California",
    index: 12,
  },
  {
    image: "/travel/highlands.jpg",
    year: 2019,
    city: "Highlands",
    country: "Scotland",
    index: 13,
  },
  {
    image: "/travel/inverness.jpg",
    year: 2019,
    city: "Inverness",
    country: "Scotland",
    index: 14,
  },
  {
    image: "/travel/manchester.jpg",
    year: 2018,
    city: "Manchester",
    country: "United Kingdom",
    index: 15,
  },
  {
    image: "/travel/salonica.jpg",
    year: 2022,
    city: "Thessaloniki",
    country: "Greece",
    index: 16,
  },
  {
    image: "/travel/santa_monica.jpg",
    year: 2017,
    city: "Los Angeles",
    country: "California",
    index: 17,
  },
  {
    image: "/travel/sithonia.jpg",
    year: 2022,
    city: "Sithonia",
    country: "Chalkidiki",
    index: 18,
  },
  {
    image: "/travel/stanley_park.jpg",
    year: 2019,
    city: "Vancouver",
    country: "Canada",
    index: 19,
  },
  {
    image: "/travel/val_thorens.jpg",
    year: 2020,
    city: "Val Thorens",
    country: "France",
    index: 20,
  },
  {
    image: "/travel/whistler_snowboard.jpg",
    year: 2019,
    city: "Whistler",
    country: "Canada",
    index: 21,
  },
  {
    image: "/travel/whistler.jpg",
    year: 2019,
    city: "Whistler",
    country: "Canada",
    index: 22,
  },
];

export default travelImages;
